### ISSUE TITLE
Homeassistant restarts with the dobiss Integration loaded

### ISSUE THREAD

**Issue by avlemos** [OpenJeDi/HomeAssistantFiles#5]
I'll be honest, the only reason I started looking into this (and I'm not even a Python programmer), is because Homeassistant restarts like every 24 hours if I have this integration loaded. It's been going for 4 days now, without restarting, but without this integration.

I'll continue to look into this (I think I seem to remember that if the Integration is stopped, the socket remains open, so that's probably where I'll look into next).

If there are any other thoughts, happy to hear (I only do lights, 23 of them).

I know this isn't the perfect place to post this, sorry for that.

**Comment by OpenJeDi** [comment]
Hi,

Thanks for doing this. At the time I wrote this code I had no Python
experience whatsoever as well. I just needed a solution to integrate my
Dobiss system into Home Assistant.

In my case, I sometimes have to restart Home Assistant because the
extension hangs and times out at startup. So there is still a lot of room
for improvement.

I am probably moving to another house soon (with a different system), so
I'm afraid I won't be able to work on it further.

Kind regards,
Jeroen


Op ma 11 mrt 2024 om 13:36 schreef André Lemos ***@***.***>:

**Comment by avlemos** [comment]
that's interesting. i've never had any issue at startup! thanks anyway

**Comment by OpenJeDi** [comment]
Maybe it was due to the socket still being open as well? I just restarted Home Assistant, not the OS.

Anyway: the strange thing is once it is started, for me, it keeps working and I never have issues.

**Comment by avlemos** [comment]
I think it's recovering from a Broken Pipe that is bringing everything down. Working on it.

**Comment by avlemos** [comment]
https://github.com/OpenJeDi/HomeAssistantFiles/pull/7 closes this

**Comment by avlemos** [comment]
forked the fork, so it only contains the actual dobiss stuff here: https://github.com/avlemos/dobiss
